# Generated by Django 5.1.6 on 2025-03-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Blog_App', '0005_alter_article_content_alter_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(max_length=250)),
                ('article', models.IntegerField()),
            ],
        ),
    ]
