# Generated by Django 5.1.6 on 2025-03-10 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Personal_Blog_App', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='name',
        ),
    ]
